// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0i4f6ts0ay3-e-_HkcMpefX2xjMNw6Ik',
    appId: '1:596065947691:web:5e478c47ff93da78369a6e',
    messagingSenderId: '596065947691',
    projectId: 'scholarpersonaltutors-e5e38',
    authDomain: 'scholarpersonaltutors-e5e38.firebaseapp.com',
    storageBucket: 'scholarpersonaltutors-e5e38.appspot.com',
    measurementId: 'G-5JCXP6TNK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfagnT4RVL_nBkrh_wVnjoW8DAdnqxY78',
    appId: '1:596065947691:android:2a9a3e81a0e93d2b369a6e',
    messagingSenderId: '596065947691',
    projectId: 'scholarpersonaltutors-e5e38',
    storageBucket: 'scholarpersonaltutors-e5e38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFhuLfJv49g5Uw4x7v3K8O3L6SzlR10Y',
    appId: '1:596065947691:ios:bd22252df607913a369a6e',
    messagingSenderId: '596065947691',
    projectId: 'scholarpersonaltutors-e5e38',
    storageBucket: 'scholarpersonaltutors-e5e38.appspot.com',
    androidClientId: '596065947691-mnkqqle45750s10en6kjlk4g2ichr0qb.apps.googleusercontent.com',
    iosClientId: '596065947691-3opv3kv612b04hhsf8num0dfua8o1eho.apps.googleusercontent.com',
    iosBundleId: 'com.scholarpersonaltutor.scholarPersonalTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFhuLfJv49g5Uw4x7v3K8O3L6SzlR10Y',
    appId: '1:596065947691:ios:02579147ba7781d6369a6e',
    messagingSenderId: '596065947691',
    projectId: 'scholarpersonaltutors-e5e38',
    storageBucket: 'scholarpersonaltutors-e5e38.appspot.com',
    androidClientId: '596065947691-mnkqqle45750s10en6kjlk4g2ichr0qb.apps.googleusercontent.com',
    iosClientId: '596065947691-g9iibvmj94rn9udrn275m0cnof0cgf8a.apps.googleusercontent.com',
    iosBundleId: 'com.scholarpersonaltutor.scholarPersonalTutor.RunnerTests',
  );
}
